CREATE OR REPLACE SCHEMA BRONZE;

-- Raw ingestion from TPCDS sample dataset
CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAW AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

-- Validate row count
SELECT COUNT(*) AS total_rows
FROM BRONZE.STORE_SALES_RAW;
LIMIT 500000;