USE DATABASE SNOWFLAKE_SAMPLE_DATA;
DESC TABLE TPCDS_SF100TCL.STORE_SALES;

SELECT COUNT(*) 
FROM TPCDS_SF100TCL.STORE_SALES;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
CREATE SCHEMA IF NOT EXISTS BRONZE;

CREATE OR REPLACE TABLE BRONZE.STORE_SALES AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 5000000000;

SELECT COUNT(*) 
FROM BRONZE.STORE_SALES;

DESC TABLE BRONZE.STORE_SALES;

SELECT COUNT(*) AS TOTAL_ROWS,
       COUNT(SS_SALES_PRICE) AS NON_NULL_SALES_PRICE
FROM BRONZE.STORE_SALES;
--OPTIONAL: You can also check for other columns, such as SS_QUANTITY, to ensure data quality.
SELECT MIN(SS_SOLD_DATE_SK) AS MIN_SOLD_DATE_SK,
       MAX(SS_SOLD_DATE_SK) AS MAX_SOLD_DATE_SK
FROM BRONZE.STORE_SALES;