-- Use database first
USE DATABASE SNOWFLAKE_SAMPLE_DATA;

-- Create schema
CREATE OR REPLACE SCHEMA BRONZE;

-- Use schema
USE SCHEMA BRONZE;

-- Raw ingestion from TPCDS sample dataset
CREATE OR REPLACE TABLE STORE_SALES_RAW AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

-- Validate row count
SELECT COUNT(*) AS total_rows
FROM STORE_SALES_RAW;